### ISSUE TITLE
关于dblp和yelp数据集的问题

### ISSUE THREAD

**Issue by frankupup** [librahu/HeGAN#1]
你好，我在阅读代码的时候发现dblp_evaluation.py 和 yelp_evaluation.py 中需要用到 dblp_ap.train_0.8_lr 和 yelp_ub.train_0.8_lr 等等数据集，但是没有找到对应的文件，请问这两个数据集如何得到呢？
感谢你所做的工作，期待你的回复

**Comment by librahu** [comment]
dblp_ap.train_0.8_lr 和 yelp_ub.train_0.8_lr 这两个数据集是做链路预测时的训练集，你可以用原始的数据集进行划分。原始的数据集见 https://github.com/librahu/HIN-Datasets-for-Recommendation-and-Network-Embedding

**Comment by frankupup** [comment]
原始的数据集了解过，非常感谢
